- name: Deploy Vulnerable AD
  hosts: windows
  vars_files: vars/variables.yml
  tasks:
  - name: Install Active Directory Domain Services
    ansible.windows.win_feature:
      name: AD-Domain-Services
      state: present

  - name: Promote Server to Domain Controller
    microsoft.ad.domain:
      dns_domain_name: "{{ domain_name }}"
      safe_mode_password: "{{ domain_passwd }}"
    register: status
  
  - name: Reboot after promotion
    ansible.windows.win_reboot:
    when: status.reboot_required
