- name: Deploy AD Users
  hosts: windows
  vars_files: vars/variables.yml
  tasks:
  # Pre-Authentication is turned off for this user
  - name: Create a vulnerable user (AS-REP Roasting candidate)
    community.windows.win_domain_user:
      name: "{{ vuln_user }}"
      password: "{{ vuln_passwd }}"
      state: present
      attributes:
        userAccountControl: 66048

  - name: Create the GPO managers group
    community.windows.win_domain_group:
      name: "{{ vuln_group }}"
      scope: global
      category: security
      state: present

  - name: Add user to the vulnerable group
    community.windows.win_domain_group_membership:
      name: "{{ vuln_group }}"
      members:
        - "{{ vuln_user }}"
      state: present

  - name: Grant group admin rights via membership
    community.windows.win_domain_group_membership:
      name: "Administrators"
      members:
        - "{{ vuln_group }}"
      state: present

  - name: Create a benign red team user 
    community.windows.win_domain_user:
      name: "{{ arasaka_user }}"
      password: "{{ arasaka_passwd }}"
      state: present

  - name: Create a benign blue team user 
    community.windows.win_domain_user:
      name: "{{ gang_user }}"
      password: "{{ gang_passwd }}"
      state: present

  - name: Create a misconfigured user with no password required
    community.windows.win_domain_user:
      name: "{{ misconf_user }}"
      # 512 (Normal) + 32 (Password Not Required) = 544
      attributes:
        userAccountControl: 544
      state: present

  - name: Set hint on the misconf_user account
    microsoft.ad.user:
      name: "{{ misconf_user }}"
      description: "LOG: Connected to Arasaka_Sync_Node. Legacy tunnel active for UID: sarasaka. Do not reset pre-auth flag."
      state: present

  - name: Set technical breadcrumb on the vuln_user
    microsoft.ad.user:
      name: "{{ vuln_user }}"
      description: "SECURITY_NOTICE: Legacy mainframe compatibility mode. Kerberos Pre-Auth: DISABLED."
      state: present